"use client";

import { FormEvent, useEffect, useState } from "react";

type AuditRecord = { id:string;timestamp:string;adminId:string|null;role:string|null;action:string;entityType:string;entityId:string|null;result:string;summary:Record<string,unknown>;request:Record<string,unknown> };
type AuditPage = { records:AuditRecord[];page:number;limit:number;hasNext:boolean };
const actionLabels:Record<string,string>={login:"Oturum açıldı",logout:"Oturum kapatıldı",failed_login:"Başarısız giriş",vehicle_create:"Araç oluşturuldu",vehicle_update:"Araç güncellendi",vehicle_image_create:"Araç görseli yüklendi",vehicle_image_update:"Araç görseli güncellendi",vehicle_image_delete:"Araç görseli silindi",featured_vehicle_change:"Öne çıkan araçlar değiştirildi",featured_article_change:"Öne çıkan bloglar değiştirildi",article_create:"Blog oluşturuldu",article_update:"Blog güncellendi",article_cover_update:"Blog kapağı güncellendi",article_cover_delete:"Blog kapağı silindi",vehicle_tag_create:"Etiket oluşturuldu",vehicle_tag_update:"Etiket güncellendi",vehicle_tag_delete:"Etiket silindi",iys_export:"İYS CSV export oluşturuldu",subscriber_unsubscribe:"Abonelik sonlandırıldı",subscriber_iys_update:"Abone İYS bilgileri güncellendi",subscriber_record_correction:"Bülten kişi kaydı düzeltildi"};
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?"Tarih bilinmiyor":new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(date)}

export function AuditLogView(){
 const[data,setData]=useState<AuditPage|null>(null),[page,setPage]=useState(1),[action,setAction]=useState(""),[result,setResult]=useState(""),[pendingFilters,setPendingFilters]=useState({action:"",result:""}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;const query=new URLSearchParams({page:String(page),limit:"20"});if(action)query.set("action",action);if(result)query.set("result",result);void fetch(`/admin-api/audit.php?${query}`,{credentials:"same-origin",cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok||!Array.isArray(payload.records))throw new Error("unavailable");if(active){setData(payload);setError("")}}).catch(()=>{if(active)setError("Loglar şu anda yüklenemiyor.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,action,result]);
 function applyFilters(event:FormEvent){event.preventDefault();setError("");if(page===1&&action===pendingFilters.action&&result===pendingFilters.result)return;setLoading(true);setPage(1);setAction(pendingFilters.action);setResult(pendingFilters.result)}
 return <section className="mt-8"><p className="text-label font-semibold text-corporate-blue">Güvenlik ve operasyon</p><h2 className="mt-1 text-heading-md">Loglar</h2><p className="mt-2 text-body text-text-secondary">Yönetim işlemlerinin salt okunur geçmişi. Bir kayda tıklayarak işlem ve istek detaylarını açabilirsiniz.</p>
  <form className="mt-6 grid gap-3 rounded-card border border-border-subtle bg-surface-card p-4 sm:grid-cols-[1fr_1fr_auto]" onSubmit={applyFilters}><label className="text-sm font-semibold">İşlem<select className="mt-1 min-h-11 w-full rounded-control border border-border-control px-3" onChange={event=>setPendingFilters(current=>({...current,action:event.target.value}))} value={pendingFilters.action}><option value="">Tüm işlemler</option>{Object.entries(actionLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold">Sonuç<select className="mt-1 min-h-11 w-full rounded-control border border-border-control px-3" onChange={event=>setPendingFilters(current=>({...current,result:event.target.value}))} value={pendingFilters.result}><option value="">Tüm sonuçlar</option><option value="success">Başarılı</option><option value="rejected">Reddedildi</option><option value="rate_limited">Sınırlandırıldı</option></select></label><button className="min-h-11 self-end rounded-control bg-brand-navy px-5 font-semibold text-white">Filtrele</button></form>
  {error?<p className="mt-5 rounded-control bg-error-surface px-4 py-3 text-error" role="alert">{error}</p>:null}{loading?<p className="mt-6 text-text-secondary">Loglar yükleniyor…</p>:null}
  {!loading&&data?<><div className="mt-6 space-y-3">{data.records.map(record=><details className="group overflow-hidden rounded-card border border-border-subtle bg-surface-card open:border-corporate-blue open:shadow-sm" key={record.id}><summary className="grid cursor-pointer list-none gap-3 p-4 hover:bg-surface-muted sm:grid-cols-[10rem_1fr_1fr_auto] sm:items-center"><time className="text-sm" dateTime={record.timestamp}>{formatDate(record.timestamp)}</time><span><strong className="block">{actionLabels[record.action]??record.action}</strong><span className="text-xs text-text-secondary">{record.adminId??"Anonim"} · {record.role??"rol yok"}</span></span><span className="text-sm">{record.entityType||"—"}{record.entityId?<small className="block text-text-secondary">{record.entityId}</small>:null}</span><span className={`w-fit rounded-pill px-3 py-1 text-xs font-semibold ${record.result==="success"?"bg-success-surface text-success":"bg-error-surface text-error"}`}>{record.result==="success"?"Başarılı":record.result}</span></summary><div className="border-t border-border-subtle bg-brand-navy p-4 text-text-inverse"><p className="mb-2 text-xs font-bold tracking-wide text-accent-orange uppercase">Log detayı</p><pre className="overflow-x-auto whitespace-pre-wrap break-words text-xs leading-6">{JSON.stringify({işlemDetayları:record.summary??{},istek:record.request??{}},null,2)}</pre></div></details>)}{!data.records.length?<p className="rounded-card border border-border-subtle bg-surface-card p-8 text-center text-text-secondary">Bu filtrelerle eşleşen log yok.</p>:null}</div><div className="mt-5 flex items-center justify-between"><button className="min-h-10 rounded-control border border-border-control px-4 disabled:opacity-40" disabled={page===1} onClick={()=>{setLoading(true);setPage(value=>value-1)}}>Önceki</button><span className="text-sm text-text-secondary">Sayfa {data.page}</span><button className="min-h-10 rounded-control border border-border-control px-4 disabled:opacity-40" disabled={!data.hasNext} onClick={()=>{setLoading(true);setPage(value=>value+1)}}>Sonraki</button></div></>:null}
 </section>
}
