/* eslint-disable @next/next/no-img-element */
"use client";
import { useEffect, useState } from "react";

type Vehicle={id:string;make:string;model:string;trim:string;publicationStatus:string;coverImage?:{src:string;alt:string}|null;draftMedia?:{id:string;alt:string}|null};
export function FeaturedVehiclesManager({csrfToken}:{csrfToken:string}){
 const[vehicles,setVehicles]=useState<Vehicle[]>([]),[ids,setIds]=useState<string[]>([]),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 useEffect(()=>{void fetch('/admin-api/featured-vehicles.php',{credentials:'same-origin',cache:'no-store'}).then(r=>r.json()).then(p=>{setVehicles(p.vehicles??[]);setIds(p.ids??[])}).catch(()=>setError('Öne çıkan araçlar yüklenemedi.'))},[]);
 const eligible=vehicles.filter(v=>v.publicationStatus==='published'&&(v.coverImage||v.draftMedia));
 function change(index:number,id:string){setSaved(false);setIds(current=>current.map((value,i)=>i===index?id:value))}
 function move(index:number,direction:number){const target=index+direction;if(target<0||target>=4)return;setIds(current=>{const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next});setSaved(false)}
 async function save(){if(ids.length!==4||new Set(ids).size!==4){setError('Tam olarak dört farklı araç seçin.');return}const r=await fetch('/admin-api/featured-vehicles.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({ids})});const p=await r.json();if(!r.ok){setError(p.error==='featured_vehicle_ineligible'?'Yalnızca yayındaki ve görseli bulunan araçlar seçilebilir.':'Tam olarak dört farklı araç seçin.');return}setError('');setSaved(true)}
 return <section className="mt-8"><p className="text-label font-semibold text-corporate-blue">Araç yönetimi</p><h2 className="mt-1 text-heading-md">Öne Çıkan Araçlar</h2><p className="mt-2 max-w-3xl text-text-secondary">Ana sayfa için tam olarak dört farklı, yayındaki ve görseli bulunan aracı sıralayın.</p>{error?<p className="mt-4 text-error">{error}</p>:null}<ol className="mt-6 grid gap-4">{[0,1,2,3].map(index=>{const selected=eligible.find(v=>v.id===ids[index]);const src=selected?.draftMedia?`/admin-api/media-file.php?id=${selected.draftMedia.id}`:selected?.coverImage?.src;return <li className="grid gap-4 rounded-card border bg-white p-4 sm:grid-cols-[3rem_8rem_1fr_auto] sm:items-center" key={index}><span className="grid size-10 place-items-center rounded-full bg-brand-navy font-bold text-white">{index+1}</span><div className="aspect-video overflow-hidden rounded-control bg-surface-muted">{src?<img className="size-full object-cover" src={src} alt=""/>:null}</div><select className="min-h-11 rounded-control border px-3" value={ids[index]??''} onChange={e=>change(index,e.target.value)}><option value="">Araç seçin</option>{eligible.map(v=><option disabled={ids.includes(v.id)&&ids[index]!==v.id} key={v.id} value={v.id}>{v.make} {v.model} · {v.trim}</option>)}</select><div className="flex gap-2"><button className="rounded-control border px-3 py-2 disabled:opacity-30" disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button className="rounded-control border px-3 py-2 disabled:opacity-30" disabled={index===3} onClick={()=>move(index,1)}>↓</button></div></li>})}</ol><button className="mt-6 min-h-12 rounded-control bg-accent-orange px-6 font-bold" onClick={save}>Sıralamayı Kaydet</button>{saved?<span className="ml-4 text-success">Kaydedildi</span>:null}</section>}
