"use client";
import { useEffect, useMemo, useState } from "react";

type Candidate={id:string;categoryId:string;title:string;status:"published"|"draft"};
type Selection={mainArticleId:string|null;categoryArticleIds:Record<string,string>};
const labels:Record<string,string>={"uzun-donem-kiralama":"Uzun Dönem Kiralama","maliyet-ve-finans":"Maliyet ve Finans","arac-rehberi":"Araç Rehberi","filo-yonetimi":"Filo Yönetimi","elektrikli-araclar":"Elektrikli Araçlar","bakim-ve-hasar":"Bakım ve Hasar"};

export function FeaturedArticlesManager({csrfToken}:{csrfToken:string}){
 const[articles,setArticles]=useState<Candidate[]>([]),[categories,setCategories]=useState<string[]>([]),[selection,setSelection]=useState<Selection>({mainArticleId:null,categoryArticleIds:{}}),[error,setError]=useState(""),[saved,setSaved]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{void fetch("/admin-api/featured-articles.php",{credentials:"same-origin",cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok||!Array.isArray(payload.articles)||!Array.isArray(payload.categories))throw new Error();setArticles(payload.articles);setCategories(payload.categories);setSelection(payload.selection)}).catch(()=>setError("Öne çıkan blog seçimleri yüklenemedi.")).finally(()=>setLoading(false))},[]);
 const ordered=useMemo(()=>[...articles].sort((a,b)=>a.title.localeCompare(b.title,"tr")),[articles]);
 async function save(){setSaved(false);setError("");const response=await fetch("/admin-api/featured-articles.php",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken},body:JSON.stringify(selection)});const payload=await response.json();if(!response.ok){setError(payload.error==="featured_articles_incomplete"?"Ana öne çıkan blogu ve her kategori için bir blogu seçin.":"Seçimler kaydedilemedi.");return}setSelection(payload.selection);setSaved(true)}
 return <section className="mt-8"><p className="text-label font-semibold text-corporate-blue">Filo Rehberi yönetimi</p><h2 className="mt-1 text-heading-md">Öne Çıkan Bloglar</h2><p className="mt-2 max-w-3xl text-text-secondary">Filo Rehberi ana alanı için bir ana içerik, kategori sayfaları için de her kategoriden bir içerik belirleyin.</p>{error?<p className="mt-4 rounded-control bg-error-surface p-3 text-error">{error}</p>:null}{loading?<p className="mt-6 text-text-secondary">Yükleniyor…</p>:<><section className="mt-6 rounded-card border-2 border-accent-orange/50 bg-accent-orange/5 p-5"><label className="font-bold">Ana Öne Çıkan<select className="mt-2 min-h-11 w-full rounded-control border bg-white px-3" value={selection.mainArticleId??""} onChange={event=>{setSaved(false);setSelection(current=>({...current,mainArticleId:event.target.value||null}))}}><option value="">Blog seçin</option>{ordered.map(article=><option key={article.id} value={article.id}>{article.title} · {labels[article.categoryId]}{article.status==="draft"?" · Draft":""}</option>)}</select></label></section><div className="mt-5 grid gap-4 md:grid-cols-2">{categories.map((category,index)=><section className="rounded-card border bg-white p-5" key={category}><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-brand-navy text-sm font-bold text-white">{index+1}</span><h3 className="font-bold">{labels[category]??category}</h3></div><select className="mt-4 min-h-11 w-full rounded-control border px-3" value={selection.categoryArticleIds[category]??""} onChange={event=>{setSaved(false);setSelection(current=>({...current,categoryArticleIds:{...current.categoryArticleIds,[category]:event.target.value}}))}}><option value="">Blog seçin</option>{ordered.filter(article=>article.categoryId===category).map(article=><option key={article.id} value={article.id}>{article.title}{article.status==="draft"?" · Draft":""}</option>)}</select></section>)}</div><button className="mt-6 min-h-12 rounded-control bg-accent-orange px-6 font-bold" onClick={()=>void save()} type="button">Seçimleri Kaydet</button>{saved?<span className="ml-4 font-semibold text-success">Kaydedildi</span>:null}</>}</section>;
}
