/* eslint-disable @next/next/no-img-element */
"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

export type LibraryMedia={id:string;originalName:string;mime:string;size:number;width:number;height:number;alt:{tr:string;en:string};usage:"article"|"vehicle"|"general";creator:string;sourcePage:string;licenseName:string;licenseUrl:string;uploadedAt:string;uploadedBy:string|null};
const control="mt-1 min-h-11 w-full rounded-control border border-border-control bg-white px-3";
export function MediaLibraryView({csrfToken,canEdit}:{csrfToken:string;canEdit:boolean}){
 const [records,setRecords]=useState<LibraryMedia[]>([]);const [query,setQuery]=useState("");const [usage,setUsage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [editing,setEditing]=useState<LibraryMedia|null>(null);
 async function load(){try{const response=await fetch("/admin-api/media.php",{credentials:"same-origin",cache:"no-store"});const payload=await response.json();if(!response.ok||!Array.isArray(payload.media))throw new Error();setRecords(payload.media);setError("");}catch{setError("Medya kütüphanesi yüklenemedi.");}}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[]);
 const shown=useMemo(()=>records.filter((record)=>(!usage||record.usage===usage)&&`${record.originalName} ${record.alt.tr} ${record.creator}`.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))),[records,query,usage]);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;setBusy(true);setError("");try{const response=await fetch("/admin-api/media.php",{method:"POST",credentials:"same-origin",headers:{"X-CSRF-Token":csrfToken},body:new FormData(formElement)});if(!response.ok)throw new Error();formElement.reset();await load();}catch{setError("Görsel yüklenemedi. JPEG, PNG veya WebP; 5 MB ve 400×225–4096×4096 sınırlarını kontrol edin.");}finally{setBusy(false);}}
 async function update(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setBusy(true);const form=new FormData(event.currentTarget);try{const response=await fetch("/admin-api/media-update.php",{method:"PATCH",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken},body:JSON.stringify({id:editing.id,altTr:form.get("altTr"),altEn:form.get("altEn"),usage:form.get("usage"),creator:form.get("creator"),sourcePage:form.get("sourcePage"),licenseName:form.get("licenseName"),licenseUrl:form.get("licenseUrl")})});if(!response.ok)throw new Error();setEditing(null);await load();}catch{setError("Medya bilgileri güncellenemedi.");}finally{setBusy(false);}}
 async function remove(record:LibraryMedia){if(!window.confirm(`“${record.originalName}” private medya kütüphanesinden silinsin mi?`))return;setBusy(true);try{const response=await fetch("/admin-api/media-delete.php",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken},body:JSON.stringify({mediaId:record.id})});if(!response.ok)throw new Error();await load();}catch{setError("Medya silinemedi. Kullanım bağlantılarını kontrol edin.");}finally{setBusy(false);}}
 return <section className="mt-8"><div><p className="text-label font-semibold text-corporate-blue">İçerik varlıkları</p><h2 className="mt-1 text-heading-md">Medya Kütüphanesi</h2><p className="mt-2 text-sm text-text-secondary">Dosyalar private staging alanında tutulur; yayınlanana kadar public siteye kopyalanmaz.</p></div>
  {canEdit?<form className="mt-6 grid gap-4 rounded-card border border-border-subtle bg-surface-card p-5 md:grid-cols-2" onSubmit={upload}><h3 className="font-bold md:col-span-2">Yeni Görsel</h3><label>Görsel *<input accept="image/jpeg,image/png,image/webp" className={control} name="image" required type="file"/></label><label>Kullanım<select className={control} defaultValue="article" name="usage"><option value="article">Filo Rehberi</option><option value="vehicle">Araç</option><option value="general">Genel</option></select></label><label className="md:col-span-2">Türkçe alternatif metin *<input className={control} maxLength={300} name="altTr" required/></label><label className="md:col-span-2">İngilizce alternatif metin<input className={control} maxLength={300} name="altEn"/></label><label>Oluşturan / fotoğrafçı<input className={control} maxLength={200} name="creator"/></label><label>Lisans adı<input className={control} maxLength={200} name="licenseName"/></label><label>Kaynak sayfası<input className={control} maxLength={500} name="sourcePage" type="url"/></label><label>Lisans URL<input className={control} maxLength={500} name="licenseUrl" type="url"/></label><button className="min-h-11 rounded-control bg-accent-orange px-5 font-bold md:col-span-2" disabled={busy}>Görseli Yükle</button></form>:null}
  <div className="mt-6 grid gap-3 rounded-card border bg-surface-card p-4 sm:grid-cols-2"><input className={control} onChange={(event)=>setQuery(event.target.value)} placeholder="Dosya, alt metin veya oluşturan ara"/><select className={control} onChange={(event)=>setUsage(event.target.value)}><option value="">Tüm kullanımlar</option><option value="article">Filo Rehberi</option><option value="vehicle">Araç</option><option value="general">Genel</option></select></div>{error?<p className="mt-4 rounded-control bg-error-surface p-4 text-error" role="alert">{error}</p>:null}
  <div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{shown.map((record)=><article className="overflow-hidden rounded-card border bg-surface-card" key={record.id}><img alt={record.alt.tr} className="aspect-video w-full object-cover" src={`/admin-api/media-file.php?id=${encodeURIComponent(record.id)}`}/><div className="p-4"><h3 className="truncate font-bold">{record.originalName}</h3><p className="mt-1 text-sm text-text-secondary">{record.width}×{record.height} · {(record.size/1048576).toFixed(2)} MB · {record.mime}</p><p className="mt-3 line-clamp-2 text-sm">{record.alt.tr}</p><div className="mt-4 flex flex-wrap gap-2"><a className="rounded-control border px-3 py-2 text-xs font-semibold" href={`/admin-api/media-file.php?id=${encodeURIComponent(record.id)}&download=1`}>İndir</a>{canEdit?<><button className="rounded-control border px-3 py-2 text-xs font-semibold" onClick={()=>setEditing(record)} type="button">Bilgileri Düzenle</button><button className="rounded-control border border-error px-3 py-2 text-xs font-semibold text-error" disabled={busy} onClick={()=>void remove(record)} type="button">Sil</button></>:null}</div></div></article>)}</div>{!shown.length?<p className="mt-6 text-text-secondary">Bu filtreye uygun private medya bulunamadı.</p>:null}
  {editing?<div className="fixed inset-0 z-50 overflow-y-auto bg-brand-navy/75 p-4"><form className="mx-auto my-8 grid max-w-2xl gap-4 rounded-card bg-page p-6 sm:grid-cols-2" onSubmit={update}><div className="sm:col-span-2 flex justify-between"><h3 className="text-xl font-bold">Medya Bilgileri</h3><button onClick={()=>setEditing(null)} type="button">Kapat</button></div><label className="sm:col-span-2">Türkçe alternatif metin *<input className={control} defaultValue={editing.alt.tr} name="altTr" required/></label><label className="sm:col-span-2">İngilizce alternatif metin<input className={control} defaultValue={editing.alt.en} name="altEn"/></label><label>Kullanım<select className={control} defaultValue={editing.usage} name="usage"><option value="article">Filo Rehberi</option><option value="vehicle">Araç</option><option value="general">Genel</option></select></label><label>Oluşturan<input className={control} defaultValue={editing.creator} name="creator"/></label><label>Lisans adı<input className={control} defaultValue={editing.licenseName} name="licenseName"/></label><label>Kaynak sayfası<input className={control} defaultValue={editing.sourcePage} name="sourcePage" type="url"/></label><label>Lisans URL<input className={control} defaultValue={editing.licenseUrl} name="licenseUrl" type="url"/></label><button className="min-h-11 rounded-control bg-accent-orange font-bold sm:col-span-2" disabled={busy}>Bilgileri Kaydet</button></form></div>:null}
 </section>;
}
