<?php
declare(strict_types=1);

function worker_assert(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
function worker_remove(string $path):void{if(!is_dir($path))return;foreach(scandir($path)?:[] as $entry){if($entry==='.'||$entry==='..')continue;$item=$path.DIRECTORY_SEPARATOR.$entry;is_dir($item)?worker_remove($item):@unlink($item);}@rmdir($path);}

$root=sys_get_temp_dir().DIRECTORY_SEPARATOR.'kalite-filo-worker-'.bin2hex(random_bytes(5));$data=$root.DIRECTORY_SEPARATOR.'data';$queues=$data.DIRECTORY_SEPARATOR.'queues';$campaigns=$data.DIRECTORY_SEPARATOR.'campaigns';mkdir($queues,0700,true);mkdir($campaigns,0700,true);
$contact=$data.DIRECTORY_SEPARATOR.'newsletter-contacts.csv';$handle=fopen($contact,'wb');fputcsv($handle,['id','email','status','consent_source','consent_text_version','consent_at','confirmed_at','unsubscribed_at','created_at','updated_at','iys_status','iys_synced_at','recipient_type']);fputcsv($handle,['1','dryrun@example.test','approved','website_newsletter','v1','2026-08-01','','','2026-08-01','2026-08-01','synced','2026-08-01','BIREYSEL']);fclose($handle);
$now=gmdate('c');$campaign=['schemaVersion'=>1,'id'=>'campaign-aabbccddeeff','name'=>'Worker test','subject'=>'Subject','preheader'=>'','content'=>[['id'=>'aabbccddeeff0011','type'=>'text','heading'=>'','text'=>'Body']],'status'=>'queued','revision'=>1,'statistics'=>['total'=>1,'pending'=>1,'sent'=>0,'failed'=>0,'skipped'=>0,'unsubscribed'=>0],'startedAt'=>null,'completedAt'=>null,'createdAt'=>$now,'updatedAt'=>$now];file_put_contents($campaigns.DIRECTORY_SEPARATOR.'campaigns.json',json_encode(['schemaVersion'=>1,'records'=>[$campaign]],JSON_THROW_ON_ERROR));
$queueId='queue-'.str_repeat('a',24);$queue=['schemaVersion'=>1,'id'=>$queueId,'idempotencyKey'=>str_repeat('b',64),'environment'=>'staging','deliveryMode'=>'dry_run','campaignId'=>$campaign['id'],'campaignRevision'=>1,'campaign'=>$campaign,'audienceFingerprint'=>str_repeat('c',64),'status'=>'queued','statistics'=>['total'=>1,'pending'=>1,'sent'=>0,'failed'=>0,'skipped'=>0],'recipients'=>[['id'=>str_repeat('d',24),'email'=>'dryrun@example.test','recipientType'=>'BIREYSEL','evidenceHash'=>str_repeat('e',64),'status'=>'pending','attempts'=>0,'lastAttemptAt'=>null,'sentAt'=>null,'failureCode'=>null]],'createdAt'=>$now,'createdBy'=>'owner','startedAt'=>null,'completedAt'=>null,'updatedAt'=>$now];file_put_contents($queues.DIRECTORY_SEPARATOR.$queueId.'.json',json_encode($queue,JSON_THROW_ON_ERROR));
$configPath=$root.DIRECTORY_SEPARATOR.'config.php';file_put_contents($configPath,"<?php return ".var_export(['environment'=>'staging','data_root'=>$data,'campaign_delivery_mode'=>'dry_run','campaign_batch_size'=>10,'users'=>[['id'=>'owner','username'=>'owner.test','display_name'=>'Owner','password_hash'=>password_hash('test password',PASSWORD_DEFAULT),'role'=>'owner','enabled'=>true]]],true).';');
try{putenv('KALITE_FILO_ADMIN_TARGET=staging');putenv('KALITE_FILO_ADMIN_CONFIG='.$configPath);putenv('KALITE_FILO_CONTACT_STORE_PATH='.$contact);$command=escapeshellarg(PHP_BINARY).' '.escapeshellarg(dirname(__DIR__).DIRECTORY_SEPARATOR.'campaign-worker.php');exec($command,$output,$status);worker_assert($status===0,'Dry-run worker must exit successfully.');$result=json_decode((string)file_get_contents($queues.DIRECTORY_SEPARATOR.$queueId.'.json'),true,40,JSON_THROW_ON_ERROR);worker_assert($result['status']==='completed'&&$result['statistics']['skipped']===1&&$result['recipients'][0]['failureCode']==='dry_run','Dry-run must reach a terminal ledger without SMTP.');}finally{putenv('KALITE_FILO_ADMIN_TARGET');putenv('KALITE_FILO_ADMIN_CONFIG');putenv('KALITE_FILO_CONTACT_STORE_PATH');worker_remove($root);}fwrite(STDOUT,"Admin campaign worker tests passed.\n");
