import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {mkdtempSync,readFileSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import path from "node:path";
import test from "node:test";
import {createVehicleMaterialization,validatePublishRequest,writeVehicleMaterialization} from "./materialize-admin-snapshot.mjs";

function request(){const vehicles=[1,2,3,4,5].map((value)=>({id:`vehicle-${value}`,sourceId:`SOURCE-${value}`,slug:`vehicle-${value}`,publicationStatus:value===5?"unpublished":"published",priceAmountMinor:value===5?null:value*10000,contentStatus:"owner-supplied",sourceStatus:value===5?"archived":"active",priority:"A",featured:value<=4,make:"Make",model:`Model ${value}`,trim:"Trim",modelYearLabel:"2026",categoryLabel:"Binek",segmentLabel:"C",fuelLabel:"Benzin",transmissionLabel:"Otomatik",powerHp:100,seats:5,summary:"Summary",featureLabels:[],dataConfidence:"high",editorialReviewRequired:false,priceStatus:value===5?"not_set":"owner-approved-list-net"}));const snapshot={formatVersion:1,vehicles,articles:[],media:[],featuredVehicleIds:["vehicle-4","vehicle-2","vehicle-1","vehicle-3"],taxonomy:{}};return{schemaVersion:1,target:"staging",snapshot,snapshotHash:createHash("sha256").update(JSON.stringify(snapshot)).digest("hex")};}

test("materializes reviewed vehicle sources deterministically",()=>{const value=request();const result=createVehicleMaterialization(value,{currency:"TRY"});assert.deepEqual(result.featuredVehicleIds,["vehicle-4","vehicle-2","vehicle-1","vehicle-3"]);assert.deepEqual(result.records.map((record)=>record.id),["vehicle-4","vehicle-2","vehicle-1","vehicle-3"]);assert.equal(result.records.some((record)=>record.id==="vehicle-5"),false);assert.deepEqual(Object.keys(result.prices.amountsMinor),["SOURCE-4","SOURCE-2","SOURCE-1","SOURCE-3"]);});
test("rejects tampering and invalid featured order",()=>{const value=request();value.snapshot.vehicles[0].model="Tampered";assert.throws(()=>validatePublishRequest(value),/hash mismatch/);const invalid=request();invalid.snapshot.featuredVehicleIds=["vehicle-1"];invalid.snapshotHash=createHash("sha256").update(JSON.stringify(invalid.snapshot)).digest("hex");assert.throws(()=>validatePublishRequest(invalid),/four unique/);});
test("writes only the three vehicle adapter outputs",()=>{const root=mkdtempSync(path.join(tmpdir(),"kalite-filo-materialize-"));try{const result=createVehicleMaterialization(request(),{currency:"TRY"});const target=writeVehicleMaterialization(root,result);assert.equal(JSON.parse(readFileSync(path.join(target,"featured-vehicle-ids.json"),"utf8")).length,4);assert.equal(JSON.parse(readFileSync(path.join(target,"vehicle-portfolio.json"),"utf8")).length,4);}finally{rmSync(root,{recursive:true,force:true});}});
