<?php
declare(strict_types=1);
require_once __DIR__.'/subscriber-store.php';

function kalite_filo_unsubscribe_token_store_path():string{return dirname(kalite_filo_contact_store_path()).DIRECTORY_SEPARATOR.'unsubscribe-tokens.json';}
/** @return list<array<string,mixed>> */
function kalite_filo_unsubscribe_token_records():array{$path=kalite_filo_unsubscribe_token_store_path();if(!is_file($path))return [];$raw=file_get_contents($path);if(!is_string($raw)||strlen($raw)>8388608)throw new RuntimeException('Unsubscribe token store is invalid.');$data=json_decode($raw,true,12,JSON_THROW_ON_ERROR);if(!is_array($data)||($data['schemaVersion']??null)!==1||!is_array($data['records']??null))throw new RuntimeException('Unsubscribe token store is invalid.');return array_values($data['records']);}
/** @param list<array<string,mixed>> $records */
function kalite_filo_write_unsubscribe_tokens(array $records):void{$path=kalite_filo_unsubscribe_token_store_path();$directory=dirname($path);if(!is_dir($directory)&&!mkdir($directory,0700,true)&&!is_dir($directory))throw new RuntimeException('Unsubscribe directory could not be created.');$temporary=$path.'.tmp-'.bin2hex(random_bytes(6));if(file_put_contents($temporary,json_encode(['schemaVersion'=>1,'records'=>array_values($records)],JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT),LOCK_EX)===false)throw new RuntimeException('Unsubscribe tokens could not be written.');@chmod($temporary,0600);if(!rename($temporary,$path)){@unlink($temporary);throw new RuntimeException('Unsubscribe tokens could not be replaced.');}@chmod($path,0600);}
function kalite_filo_issue_unsubscribe_token(string $email):string{$email=strtolower(trim($email));if(filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new InvalidArgumentException('Invalid email.');$path=kalite_filo_unsubscribe_token_store_path();$directory=dirname($path);if(!is_dir($directory)&&!mkdir($directory,0700,true)&&!is_dir($directory))throw new RuntimeException('Unsubscribe directory could not be created.');$lock=fopen($path.'.lock','c+');if($lock===false||!flock($lock,LOCK_EX))throw new RuntimeException('Unsubscribe token store could not be locked.');try{$records=kalite_filo_unsubscribe_token_records();$token=bin2hex(random_bytes(32));$records[]=['id'=>bin2hex(random_bytes(16)),'tokenHash'=>hash('sha256',$token),'email'=>$email,'createdAt'=>gmdate('c'),'usedAt'=>null];if(count($records)>100000)$records=array_slice($records,-100000);kalite_filo_write_unsubscribe_tokens($records);return $token;}finally{flock($lock,LOCK_UN);fclose($lock);}}
function kalite_filo_suppress_contact_email(string $email):bool{$email=strtolower(trim($email));if(filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new InvalidArgumentException('Invalid email.');$path=kalite_filo_contact_store_path();if(!is_file($path))return false;$lock=fopen($path.'.lock','c+');if($lock===false||!flock($lock,LOCK_EX))throw new RuntimeException('Contact store could not be locked.');try{$input=fopen($path,'rb');if($input===false)throw new RuntimeException('Contact store could not be read.');$columns=kalite_filo_contact_store_columns();$header=fgetcsv($input);$legacy=array_slice($columns,0,-1);if($header!==$columns&&$header!==$legacy){fclose($input);throw new RuntimeException('Contact store schema is not recognized.');}$rows=[];$changed=false;$now=gmdate('Y-m-d H:i:s');while(($values=fgetcsv($input))!==false){if($header===$legacy&&count($values)===count($legacy))$values[]='BIREYSEL';if(count($values)!==count($columns))continue;$row=array_combine($columns,$values);if(!is_array($row))continue;if(strtolower(trim($row['email']))===$email){$row['status']='unsubscribed';$row['unsubscribed_at']=$row['unsubscribed_at']!==''?$row['unsubscribed_at']:$now;$row['updated_at']=$now;$changed=true;}$rows[]=$row;}fclose($input);if(!$changed)return false;$temporary=$path.'.tmp-'.bin2hex(random_bytes(6));$output=fopen($temporary,'xb');if($output===false)throw new RuntimeException('Contact store temporary file failed.');fputcsv($output,$columns);foreach($rows as $row)fputcsv($output,array_map(static fn(string $column):string=>(string)$row[$column],$columns));fflush($output);fclose($output);@chmod($temporary,0600);if(!rename($temporary,$path)){@unlink($temporary);throw new RuntimeException('Contact store could not be replaced.');}@chmod($path,0600);return true;}finally{flock($lock,LOCK_UN);fclose($lock);}}
function kalite_filo_consume_unsubscribe_token(string $token):bool{if(preg_match('/^[a-f0-9]{64}$/',$token)!==1)return false;$path=kalite_filo_unsubscribe_token_store_path();$lock=fopen($path.'.lock','c+');if($lock===false||!flock($lock,LOCK_EX))throw new RuntimeException('Unsubscribe token store could not be locked.');try{$records=kalite_filo_unsubscribe_token_records();$hash=hash('sha256',$token);$email=null;foreach($records as &$record)if(is_string($record['tokenHash']??null)&&hash_equals($record['tokenHash'],$hash)){$email=(string)($record['email']??'');$record['usedAt']??=gmdate('c');break;}unset($record);if($email===null)return false;$changed=kalite_filo_suppress_contact_email($email);kalite_filo_write_unsubscribe_tokens($records);return $changed||filter_var($email,FILTER_VALIDATE_EMAIL)!==false;}finally{flock($lock,LOCK_UN);fclose($lock);}}
