<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';require_once __DIR__.'/read-model.php';require_once __DIR__.'/article-store.php';require_once __DIR__.'/article-media-store.php';
$pendingPath=null;
try{
 kalite_filo_admin_start_session();kalite_filo_admin_require_authentication();kalite_filo_admin_require_roles(['owner','admin','editor']);$method=$_SERVER['REQUEST_METHOD']??'';if(!in_array($method,['POST','DELETE'],true))kalite_filo_admin_json(['error'=>'method_not_allowed'],405);kalite_filo_admin_require_same_origin();kalite_filo_admin_require_csrf();$body=$method==='POST'?$_POST:kalite_filo_admin_read_json();$articleId=trim((string)($body['articleId']??''));
 $articleLock=kalite_filo_admin_lock_article_store();try{$drafts=kalite_filo_admin_article_drafts();$index=null;foreach($drafts as $candidateIndex=>$candidate)if(($candidate['id']??null)===$articleId){$index=$candidateIndex;break;}if(!is_int($index))kalite_filo_admin_json(['error'=>'not_found'],404);$before=$drafts[$index];$oldId=is_string($before['coverMediaId']??null)?$before['coverMediaId']:null;$oldMedia=null;foreach(kalite_filo_admin_article_media_records() as $candidate)if(($candidate['id']??null)===$oldId){$oldMedia=$candidate;break;}
  if($method==='POST'){$upload=$_FILES['image']??null;if(!is_array($upload)||($upload['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file((string)$upload['tmp_name']))throw new InvalidArgumentException('upload');$inspection=kalite_filo_admin_inspect_article_image((string)$upload['tmp_name'],(int)$upload['size']);$id=bin2hex(random_bytes(16));$pendingPath=kalite_filo_admin_article_media_path($id,'webp');kalite_filo_admin_ensure_private_directory(dirname($pendingPath));if(!move_uploaded_file((string)$upload['tmp_name'],$pendingPath))throw new RuntimeException('Cover could not be stored.');@chmod($pendingPath,0600);$altTr=trim((string)($body['altTr']??''));$altEn=trim((string)($body['altEn']??''));if($altTr===''||mb_strlen($altTr)>300||mb_strlen($altEn)>300)throw new InvalidArgumentException('metadata');$record=['id'=>$id,'articleId'=>$articleId,'originalName'=>mb_substr(basename((string)$upload['name']),0,255),'extension'=>'webp','mime'=>'image/webp','size'=>(int)filesize($pendingPath),'width'=>$inspection['width'],'height'=>$inspection['height'],'checksum'=>hash_file('sha256',$pendingPath),'alt'=>['tr'=>$altTr,'en'=>$altEn],'usage'=>'article','rightsBasis'=>'user-provided-for-site-use','uploadedAt'=>gmdate('c'),'uploadedBy'=>$_SESSION['identity']['id']??null];$mediaLock=kalite_filo_admin_lock_article_media_store();try{$records=kalite_filo_admin_article_media_records();$records=array_values(array_filter($records,static fn(array $item):bool=>($item['id']??null)!==$oldId));$records[]=$record;kalite_filo_admin_write_article_media_records($records);}finally{kalite_filo_admin_unlock_article_media_store($mediaLock);}$drafts[$index]['coverMediaId']=$id;$drafts[$index]['coverRemoved']=false;$action='article_cover_update';$summary=['id'=>$articleId,'mediaId'=>$id,'fileName'=>$record['originalName'],'size'=>$record['size'],'dimensions'=>'1600x900'];}
  else{$mediaLock=kalite_filo_admin_lock_article_media_store();try{$records=kalite_filo_admin_article_media_records();$records=array_values(array_filter($records,static fn(array $item):bool=>($item['id']??null)!==$oldId));kalite_filo_admin_write_article_media_records($records);}finally{kalite_filo_admin_unlock_article_media_store($mediaLock);}$drafts[$index]['coverMediaId']=null;$drafts[$index]['coverRemoved']=true;$record=null;$action='article_cover_delete';$summary=['id'=>$articleId,'mediaId'=>$oldId];}
  $drafts[$index]['revision']=(int)($drafts[$index]['revision']??0)+1;$drafts[$index]['updatedAt']=gmdate('c');$drafts[$index]['updatedBy']=$_SESSION['identity']['id']??null;kalite_filo_admin_write_article_revision('update',$drafts[$index],$before);kalite_filo_admin_write_article_drafts($drafts);$article=$drafts[$index];
 }finally{kalite_filo_admin_unlock_article_store($articleLock);}
 if($oldId!==null&&is_array($oldMedia))@unlink(kalite_filo_admin_article_media_path($oldId,(string)$oldMedia['extension']));$pendingPath=null;kalite_filo_admin_audit($action,'success',$summary);kalite_filo_admin_json(['article'=>$article,'media'=>$record],$method==='POST'?201:200);
}catch(InvalidArgumentException $e){if(is_string($pendingPath))@unlink($pendingPath);kalite_filo_admin_json(['error'=>$e->getMessage()],422);}catch(Throwable $e){if(is_string($pendingPath))@unlink($pendingPath);error_log('Article cover operation failed: '.$e->getMessage());kalite_filo_admin_json(['error'=>'service_unavailable'],503);}
