<?php
declare(strict_types=1);
const KALITE_FILO_CAMPAIGN_STATUSES=['draft','queued','sending','completed','partially_failed','cancelled'];
function kalite_filo_admin_campaign_store_path():string{return (string)kalite_filo_admin_config()['data_root'].DIRECTORY_SEPARATOR.'campaigns'.DIRECTORY_SEPARATOR.'campaigns.json';}
/** @return resource */
function kalite_filo_admin_lock_campaign_store(){$path=kalite_filo_admin_campaign_store_path();kalite_filo_admin_ensure_private_directory(dirname($path));$handle=fopen($path.'.lock','c+');if($handle===false||!flock($handle,LOCK_EX)){if(is_resource($handle))fclose($handle);throw new RuntimeException('Campaign store could not be locked.');}@chmod($path.'.lock',0600);return $handle;}
/** @param resource $handle */ function kalite_filo_admin_unlock_campaign_store($handle):void{flock($handle,LOCK_UN);fclose($handle);}
/** @return list<array<string,mixed>> */
function kalite_filo_admin_campaign_records():array{$path=kalite_filo_admin_campaign_store_path();if(!is_file($path))return [];$raw=file_get_contents($path);if(!is_string($raw)||strlen($raw)>16777216)throw new RuntimeException('Campaign store is invalid.');$data=json_decode($raw,true,30,JSON_THROW_ON_ERROR);if(!is_array($data)||($data['schemaVersion']??null)!==1||!is_array($data['records']??null))throw new RuntimeException('Campaign store is invalid.');return array_values($data['records']);}
/** @param list<array<string,mixed>> $records */
function kalite_filo_admin_write_campaign_records(array $records):void{$path=kalite_filo_admin_campaign_store_path();kalite_filo_admin_ensure_private_directory(dirname($path));$temporary=$path.'.tmp-'.bin2hex(random_bytes(6));if(file_put_contents($temporary,json_encode(['schemaVersion'=>1,'records'=>array_values($records)],JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX)===false)throw new RuntimeException('Campaign store could not be written.');@chmod($temporary,0600);if(!rename($temporary,$path)){@unlink($temporary);throw new RuntimeException('Campaign store could not be replaced.');}}
function kalite_filo_admin_campaign_text(mixed $value,int $max,bool $required=false):string{if(!is_string($value)){if($required)throw new InvalidArgumentException('Missing campaign field.');return '';}$value=trim($value);if($required&&$value==='')throw new InvalidArgumentException('Missing campaign field.');if(mb_strlen($value)>$max||preg_match('/[\r\n]/',$value)===1&&$max<=300)throw new InvalidArgumentException('Invalid campaign field.');return $value;}
/** @return list<array<string,mixed>> */
function kalite_filo_admin_normalize_campaign_blocks(mixed $input):array{if(!is_array($input)||count($input)<1||count($input)>30)throw new InvalidArgumentException('Campaign blocks are required.');$result=[];foreach($input as $block){if(!is_array($block)||!in_array($block['type']??null,['hero','text','cta','divider','vehicle_cards','article_cards'],true))throw new InvalidArgumentException('Invalid campaign block.');$type=$block['type'];$normalized=['id'=>is_string($block['id']??null)&&preg_match('/^[a-f0-9]{16}$/',$block['id'])===1?$block['id']:bin2hex(random_bytes(8)),'type'=>$type];if(in_array($type,['hero','text'],true)){$normalized['heading']=kalite_filo_admin_campaign_text($block['heading']??'',160,$type==='hero');$normalized['text']=kalite_filo_admin_campaign_text($block['text']??'',4000,true);}elseif($type==='cta'){$normalized['label']=kalite_filo_admin_campaign_text($block['label']??'',80,true);$url=kalite_filo_admin_campaign_text($block['url']??'',500,true);if(filter_var($url,FILTER_VALIDATE_URL)===false)throw new InvalidArgumentException('Invalid campaign URL.');$normalized['url']=$url;}elseif(in_array($type,['vehicle_cards','article_cards'],true)){$ids=$block['entityIds']??null;if(!is_array($ids)||count($ids)<1||count($ids)>8)throw new InvalidArgumentException('Campaign card references are required.');$normalized['entityIds']=array_values(array_unique(array_map(static function($id):string{if(!is_string($id)||preg_match('/^[a-z0-9][a-z0-9_-]{1,120}$/',$id)!==1)throw new InvalidArgumentException('Invalid campaign reference.');return $id;},$ids)));}$result[]=$normalized;}return $result;}
/** @return array<string,mixed> */
function kalite_filo_admin_normalize_campaign(array $input,?array $existing=null):array{if($existing!==null&&($existing['status']??'draft')!=='draft')throw new InvalidArgumentException('Only draft campaigns can be edited.');$now=gmdate('c');return ['schemaVersion'=>1,'id'=>$existing['id']??('campaign-'.bin2hex(random_bytes(6))),'name'=>kalite_filo_admin_campaign_text($input['name']??'',160,true),'subject'=>kalite_filo_admin_campaign_text($input['subject']??'',180,true),'preheader'=>kalite_filo_admin_campaign_text($input['preheader']??'',240),'content'=>kalite_filo_admin_normalize_campaign_blocks($input['content']??null),'status'=>'draft','audience'=>['type'=>'eligible_marketing_contacts'],'statistics'=>['total'=>0,'pending'=>0,'sent'=>0,'failed'=>0,'skipped'=>0,'unsubscribed'=>0],'scheduledAt'=>null,'startedAt'=>null,'completedAt'=>null,'revision'=>(int)($existing['revision']??0)+1,'createdAt'=>$existing['createdAt']??$now,'updatedAt'=>$now,'updatedBy'=>$_SESSION['identity']['id']??null];}

/** @param array<string,mixed> $campaign @param array<string,mixed> $snapshot @return array<string,mixed> */
function kalite_filo_admin_freeze_campaign_references(array $campaign,array $snapshot):array{$vehicles=$snapshot['vehicles']['records']??[];$articles=$snapshot['articles']['records']??[];if(!is_array($vehicles)||!is_array($articles))throw new RuntimeException('Content snapshot is invalid.');foreach($campaign['content'] as &$block){$type=$block['type']??'';if(!in_array($type,['vehicle_cards','article_cards'],true))continue;$items=[];foreach($block['entityIds'] as $id){$source=null;foreach($type==='vehicle_cards'?$vehicles:$articles as $record)if(is_array($record)&&($record['id']??null)===$id){$source=$record;break;}if(!is_array($source)||($source['publicationStatus']??'published')!=='published')throw new InvalidArgumentException('Campaign reference is not published.');$cover=$source['coverImage']??null;if($type==='vehicle_cards')$items[]=['id'=>$id,'title'=>trim((string)($source['make']??'').' '.(string)($source['model']??'')),'summary'=>(string)($source['summary']??''),'url'=>'/arac-listesi/'.(string)($source['slug']??'').'/', 'image'=>is_array($cover)?['src'=>(string)($cover['src']??''),'alt'=>(string)($cover['alt']??'')]:null];else $items[]=['id'=>$id,'title'=>(string)($source['title']??''),'summary'=>(string)($source['excerpt']??''),'url'=>'/filo-rehberi/'.(string)($source['categoryId']??'').'/'.(string)($source['slug']??'').'/', 'image'=>is_array($cover)?['src'=>(string)($cover['src']??''),'alt'=>(string)($cover['alt']??'')]:null];}$block['frozenItems']=$items;}unset($block);$campaign['referencesFrozenAt']=gmdate('c');return $campaign;}
/** @param array<string,mixed> $snapshot @return array<string,list<array<string,string>>> */
function kalite_filo_admin_campaign_reference_options(array $snapshot):array{$vehicles=[];foreach($snapshot['vehicles']['records']??[] as $record)if(is_array($record)&&($record['publicationStatus']??'')==='published')$vehicles[]=['id'=>(string)$record['id'],'label'=>trim((string)($record['make']??'').' '.(string)($record['model']??''))];$articles=[];foreach($snapshot['articles']['records']??[] as $record)if(is_array($record)&&($record['publicationStatus']??'published')==='published')$articles[]=['id'=>(string)$record['id'],'label'=>(string)($record['title']??'')];return ['vehicles'=>$vehicles,'articles'=>$articles];}
function kalite_filo_admin_campaign_escape(string $value):string{return htmlspecialchars($value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
/** @param array<string,mixed> $campaign */
function kalite_filo_admin_render_campaign_html(array $campaign,string $origin):string{$body='';foreach($campaign['content'] as $block){$type=$block['type'];if($type==='divider'){$body.='<hr style="border:0;border-top:1px solid #dbe1ea;margin:28px 0">';continue;}if($type==='cta'){$body.='<p><a href="'.kalite_filo_admin_campaign_escape((string)$block['url']).'" style="display:inline-block;background:#f6a623;color:#101a33;text-decoration:none;padding:13px 22px;border-radius:9px;font-weight:700">'.kalite_filo_admin_campaign_escape((string)$block['label']).'</a></p>';continue;}if(in_array($type,['vehicle_cards','article_cards'],true)){$body.='<table role="presentation" width="100%">';foreach($block['frozenItems']??[] as $item){$body.='<tr><td style="padding:12px 0"><h3 style="margin:0 0 6px;color:#101a33">'.kalite_filo_admin_campaign_escape((string)$item['title']).'</h3><p style="margin:0 0 8px;color:#526077;line-height:1.5">'.kalite_filo_admin_campaign_escape((string)$item['summary']).'</p><a href="'.kalite_filo_admin_campaign_escape($origin.(string)$item['url']).'" style="color:#174a7c">İncele</a></td></tr>';}$body.='</table>';continue;}$heading=(string)($block['heading']??'');if($heading!=='')$body.='<h2 style="color:#101a33;margin:24px 0 8px">'.kalite_filo_admin_campaign_escape($heading).'</h2>';$body.='<p style="color:#526077;line-height:1.65;white-space:pre-line">'.kalite_filo_admin_campaign_escape((string)($block['text']??'')).'</p>';}$subject=kalite_filo_admin_campaign_escape((string)$campaign['subject']);return '<!doctype html><html><body style="margin:0;background:#eef1f5;font-family:Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden">'.kalite_filo_admin_campaign_escape((string)$campaign['preheader']).'</div><table role="presentation" width="100%"><tr><td align="center" style="padding:24px"><table role="presentation" width="640" style="max-width:100%;background:#fff;border-radius:16px"><tr><td style="background:#101a33;color:#fff;padding:24px 32px"><strong style="font-size:22px">Kalite Filo</strong></td></tr><tr><td style="padding:32px"><h1 style="color:#101a33;margin-top:0">'.$subject.'</h1>'.$body.'<hr style="border:0;border-top:1px solid #dbe1ea;margin:32px 0"><p style="font-size:12px;color:#718096">Bu bir kampanya önizlemesidir. İletişim bilgileri ve kişiye özel abonelikten ayrılma bağlantısı gönderim sırasında zorunlu olarak eklenir.</p></td></tr></table></td></tr></table></body></html>';}
/** @param list<array<string,string>> $rows @return array<string,int> */
function kalite_filo_admin_campaign_audience_summary(array $rows,string $environment):array{$emails=[];foreach($rows as $row){$email=strtolower(trim((string)($row['email']??'')));if(filter_var($email,FILTER_VALIDATE_EMAIL)===false)continue;$state=$emails[$email]??['unsubscribed'=>false,'eligible'=>false,'missingConsent'=>false,'iysBlocked'=>false];$unsubscribed=($row['status']??'')==='unsubscribed'||trim((string)($row['unsubscribed_at']??''))!=='';$state['unsubscribed']=$state['unsubscribed']||$unsubscribed;$hasConsent=in_array($row['status']??'', ['approved','active'],true)&&trim((string)($row['consent_at']??''))!==''&&trim((string)($row['consent_text_version']??''))!=='';$iysOk=in_array($row['iys_status']??'', ['approved','synced'],true);if($hasConsent&&$iysOk)$state['eligible']=true;elseif(!$hasConsent)$state['missingConsent']=true;else $state['iysBlocked']=true;$emails[$email]=$state;}$summary=['uniqueContacts'=>count($emails),'eligible'=>0,'sendable'=>0,'unsubscribed'=>0,'missingConsent'=>0,'iysBlocked'=>0,'environmentBlocked'=>0];foreach($emails as $state){if($state['unsubscribed']){$summary['unsubscribed']++;continue;}if($state['eligible']){$summary['eligible']++;if($environment==='production')$summary['sendable']++;else $summary['environmentBlocked']++;}elseif($state['missingConsent'])$summary['missingConsent']++;else $summary['iysBlocked']++;}return $summary;}
