<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';require_once __DIR__.'/read-model.php';require_once __DIR__.'/vehicle-store.php';require_once __DIR__.'/vehicle-media.php';require_once __DIR__.'/media-store.php';require_once __DIR__.'/article-store.php';
try{
 kalite_filo_admin_require_method('POST');kalite_filo_admin_require_same_origin();kalite_filo_admin_start_session();kalite_filo_admin_require_authentication();kalite_filo_admin_require_csrf();kalite_filo_admin_require_roles(['owner','admin','editor']);$body=kalite_filo_admin_read_json();$mediaId=(string)($body['mediaId']??'');
 if($mediaId!==''){
  foreach(kalite_filo_admin_article_drafts() as $article)if(($article['coverMediaId']??null)===$mediaId)kalite_filo_admin_json(['error'=>'media_in_use'],409);
  $lock=kalite_filo_admin_lock_media_store();try{$records=kalite_filo_admin_media_records();$media=null;$remaining=[];foreach($records as $record){if(($record['id']??'')===$mediaId)$media=$record;else $remaining[]=$record;}if(!is_array($media))kalite_filo_admin_json(['error'=>'not_found'],404);kalite_filo_admin_write_media_records($remaining);}finally{kalite_filo_admin_unlock_media_store($lock);}
  @unlink(kalite_filo_admin_media_path($mediaId,(string)$media['extension']));kalite_filo_admin_audit('media_delete','success',['id'=>$mediaId]);kalite_filo_admin_json(['deleted'=>true]);
 }
 $vehicleId=(string)($body['vehicleId']??'');$requestedMediaId=(string)($body['mediaId']??'');$records=kalite_filo_admin_vehicle_records();$media=null;foreach($records as &$record)if(($record['id']??'')===$vehicleId){$gallery=is_array($record['galleryMedia']??null)?array_values($record['galleryMedia']):(is_array($record['draftMedia']??null)?[$record['draftMedia']]:[]);$remaining=[];foreach($gallery as $candidate){if(!is_array($candidate))continue;if($media===null&&($requestedMediaId===''||($candidate['id']??'')===$requestedMediaId))$media=$candidate;else $remaining[]=$candidate;}if($remaining===[]){unset($record['galleryMedia'],$record['draftMedia']);}else{$record['galleryMedia']=$remaining;$record['draftMedia']=$remaining[0];}break;}unset($record);if(!is_array($media))kalite_filo_admin_json(['error'=>'not_found'],404);kalite_filo_admin_write_vehicle_records($records);@unlink(kalite_filo_admin_vehicle_media_path((string)$media['id'],(string)$media['extension']));kalite_filo_admin_audit('vehicle_image_delete','success',['id'=>$vehicleId,'mediaId'=>$media['id']??null]);kalite_filo_admin_json(['deleted'=>true]);
}catch(Throwable $e){error_log('Media delete failed: '.$e->getMessage());kalite_filo_admin_json(['error'=>'service_unavailable'],503);}
