<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';require_once __DIR__.'/vehicle-store.php';require_once __DIR__.'/article-store.php';require_once __DIR__.'/media-store.php';require_once __DIR__.'/taxonomy-store.php';require_once __DIR__.'/featured-article-store.php';require_once __DIR__.'/publishing-store.php';

/** @param list<string> $ids */
function kalite_filo_admin_restore_featured_vehicle_ids(array $ids):void{$path=(string)kalite_filo_admin_config()['data_root'].DIRECTORY_SEPARATOR.'drafts'.DIRECTORY_SEPARATOR.'featured-vehicles.json';kalite_filo_admin_ensure_private_directory(dirname($path));$tmp=$path.'.tmp-'.bin2hex(random_bytes(5));$payload=['schemaVersion'=>1,'ids'=>$ids,'updatedAt'=>gmdate('c'),'updatedBy'=>$_SESSION['identity']['id']??null];if(file_put_contents($tmp,json_encode($payload,JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT),LOCK_EX)===false||!rename($tmp,$path)){@unlink($tmp);throw new RuntimeException('Featured vehicle store could not be restored.');}@chmod($path,0600);}
function kalite_filo_admin_update_revert_baseline_fingerprint(string $type,string $path):void{$baselinePath=kalite_filo_admin_publish_baseline_path();$record=kalite_filo_admin_publish_baseline_record();if($record===[]||!is_file($path))throw new RuntimeException('Publishing baseline is unavailable.');$record['fingerprints'][$type]=hash_file('sha256',$path);$record['updatedAt']=gmdate('c');$tmp=$baselinePath.'.tmp-'.bin2hex(random_bytes(5));if(file_put_contents($tmp,json_encode($record,JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT),LOCK_EX)===false||!rename($tmp,$baselinePath)){@unlink($tmp);throw new RuntimeException('Publishing baseline could not be updated.');}@chmod($baselinePath,0600);}

try{kalite_filo_admin_require_method('POST');kalite_filo_admin_start_session();kalite_filo_admin_require_roles(['owner','admin']);kalite_filo_admin_require_same_origin();kalite_filo_admin_require_csrf();$body=kalite_filo_admin_read_json();$type=$body['type']??null;$changeId=$body['changeId']??null;if(($body['confirmation']??null)!=='DRAFT DEĞİŞİKLİKLERİNİ GERİ AL'||!is_string($type)||!is_string($changeId))throw new InvalidArgumentException('invalid_confirmation');
foreach(kalite_filo_admin_publish_requests() as $request)if(kalite_filo_admin_publish_request_is_in_flight($request))kalite_filo_admin_json(['error'=>'publish_in_progress'],409);
$current=null;foreach(kalite_filo_admin_unpublished_changes() as $change)if(($change['type']??null)===$type&&hash_equals((string)$change['id'],$changeId)){$current=$change;break;}if($current===null)kalite_filo_admin_json(['error'=>'change_changed'],409);$snapshot=kalite_filo_admin_previous_publish_snapshot();if($snapshot===null)kalite_filo_admin_json(['error'=>'baseline_unavailable'],409);
$path='';switch($type){case'vehicles':kalite_filo_admin_write_vehicle_records(is_array($snapshot['vehicles']??null)?$snapshot['vehicles']:[]);$path=kalite_filo_admin_vehicle_store_path();break;case'articles':kalite_filo_admin_write_article_drafts(is_array($snapshot['articles']??null)?$snapshot['articles']:[]);$path=kalite_filo_admin_article_store_path();break;case'media':kalite_filo_admin_write_media_records(is_array($snapshot['media']??null)?$snapshot['media']:[]);$path=kalite_filo_admin_media_catalog_path();break;case'vehicle_taxonomy':kalite_filo_admin_write_taxonomy(is_array($snapshot['taxonomy']??null)?$snapshot['taxonomy']:[]);$path=kalite_filo_admin_taxonomy_path();break;case'featured_vehicles':kalite_filo_admin_restore_featured_vehicle_ids(is_array($snapshot['featuredVehicleIds']??null)?array_values($snapshot['featuredVehicleIds']):[]);$path=(string)kalite_filo_admin_config()['data_root'].DIRECTORY_SEPARATOR.'drafts'.DIRECTORY_SEPARATOR.'featured-vehicles.json';break;case'featured_articles':$selection=is_array($snapshot['featuredArticles']??null)?$snapshot['featuredArticles']:['mainArticleId'=>null,'categoryArticleIds'=>[]];kalite_filo_admin_write_featured_articles_selection($selection);$path=kalite_filo_admin_featured_articles_path();break;default:throw new InvalidArgumentException('unsupported_change');}
kalite_filo_admin_update_revert_baseline_fingerprint($type,$path);kalite_filo_admin_audit('publishing_change_revert','success',['type'=>$type,'changeId'=>$changeId]);kalite_filo_admin_json(['reverted'=>true,'type'=>$type]);
}catch(InvalidArgumentException $e){kalite_filo_admin_json(['error'=>$e->getMessage()],422);}catch(Throwable $e){error_log('Publishing change revert failed: '.$e->getMessage());kalite_filo_admin_json(['error'=>'service_unavailable'],503);}
