<?php
declare(strict_types=1);
const KALITE_FILO_TAXONOMY_FIELDS=['make','model','modelYearLabel','categoryLabel','segmentLabel','fuelLabel','transmissionLabel','seats'];
function kalite_filo_admin_taxonomy_path():string{return (string)kalite_filo_admin_config()['data_root'].DIRECTORY_SEPARATOR.'drafts'.DIRECTORY_SEPARATOR.'vehicle-taxonomy.json';}
function kalite_filo_admin_taxonomy_id(string $field,string $value):string{return substr(hash('sha256',$field."\0".$value),0,24);}
/** @return array<string,list<array{id:string,value:string,custom:bool,usageCount:int}>> */
function kalite_filo_admin_taxonomy():array{$records=kalite_filo_admin_vehicle_records();$custom=[];$path=kalite_filo_admin_taxonomy_path();if(is_file($path)){$raw=json_decode((string)file_get_contents($path),true,8,JSON_THROW_ON_ERROR);if(is_array($raw)&&($raw['schemaVersion']??null)===1&&is_array($raw['values']??null))$custom=$raw['values'];}$result=[];foreach(KALITE_FILO_TAXONOMY_FIELDS as $field){$values=[];foreach($records as $vehicle){$value=trim((string)($vehicle[$field]??''));if($value!=='')$values[$value]=($values[$value]??0)+1;}foreach(($custom[$field]??[]) as $value)if(is_string($value)&&trim($value)!=='')$values[trim($value)]??=0;ksort($values,SORT_NATURAL|SORT_FLAG_CASE);$result[$field]=[];foreach($values as $value=>$count)$result[$field][]=['id'=>kalite_filo_admin_taxonomy_id($field,$value),'value'=>$value,'custom'=>in_array($value,$custom[$field]??[],true),'usageCount'=>$count];}return $result;}
/** @param array<string,list<string>> $values */
function kalite_filo_admin_write_taxonomy(array $values):void{$path=kalite_filo_admin_taxonomy_path();kalite_filo_admin_ensure_private_directory(dirname($path));$tmp=$path.'.tmp-'.bin2hex(random_bytes(5));file_put_contents($tmp,json_encode(['schemaVersion'=>1,'values'=>$values],JSON_THROW_ON_ERROR|JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);@chmod($tmp,0600);if(!rename($tmp,$path)){@unlink($tmp);throw new RuntimeException('Taxonomy store could not be replaced.');}}
/** @return array<string,list<string>> */
function kalite_filo_admin_custom_taxonomy():array{$path=kalite_filo_admin_taxonomy_path();if(!is_file($path))return[];$raw=json_decode((string)file_get_contents($path),true,8,JSON_THROW_ON_ERROR);return is_array($raw['values']??null)?$raw['values']:[];}
